### PR TITLE
Add June 2017 post.

### PR DESCRIPTION
**Pull request by ClaytonJY**
WFM

### CODE REVIEW

**Comment by ellisvalentiner** [comment]
I'm. It sure those links will be correct after merging with master.

**Comment by ClaytonJY** [comment]
@ellisvalentiner the rawgit ones? Neither of those point to this repo, so merging this can't affect them.

**Comment by ellisvalentiner** [comment]
Oh right. I just noticed they didn't quite match the format of the other ones...

**Review by ellisvalentiner — APPROVED** [review]

**Comment by ClaytonJY** [comment]
I think they match the format of all the ones I make. According to rawgit, best practice is to only use commit-specific links with the production version of rawgit, never the branch-specific ones, because the latter can change but once you visit a prod rawgit link it is frozen to that version permanently.

**Pull request merged**
